export type FarmingData = {
  seed_id: number
  level: number
  cost: string
  xp: number
  time: number
  sells_for: string
  seed: string
  grows_id: number
  grows: string
  buy_from: string
  buy_from_id: number
  sell_to: string
  sell_to_id: number
}

const farmingData = [
  {
    "seed_id": 754,
    "level": 1,
    "cost": 6,
    "xp": 5,
    "time": 3,
    "sells_for": 5,
    "seed": "Green Leaf Seed",
    "grows_id": 220,
    "grows": "Green Leaf",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Reval Alchemist",
    "sell_to_id": 77
  },
  {
    "seed_id": 756,
    "level": 1,
    "cost": 2,
    "xp": 5,
    "time": 3,
    "sells_for": 5,
    "seed": "Grass Seed",
    "grows_id": 282,
    "grows": "Grass",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Farmer",
    "sell_to_id": 182
  },
  {
    "seed_id": 1867,
    "level": 1,
    "cost": "",
    "xp": 75,
    "time": 60,
    "sells_for": "",
    "seed": "Pumpkin Seed",
    "grows_id": 1868,
    "grows": "Pumpkin",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 1154,
    "level": 1,
    "cost": "",
    "xp": 350,
    "time": 240,
    "sells_for": "",
    "seed": "Rose Seed",
    "grows_id": 1157,
    "grows": "Rose",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 755,
    "level": 2,
    "cost": 12,
    "xp": 8,
    "time": 4,
    "sells_for": 10,
    "seed": "Yellow Leaf Seed",
    "grows_id": 204,
    "grows": "Yellow Leaf",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Reval Alchemist",
    "sell_to_id": 77
  },
  {
    "seed_id": 1034,
    "level": 3,
    "cost": 240,
    "xp": 10,
    "time": 5,
    "sells_for": 150,
    "seed": "Cotton Seed",
    "grows_id": 265,
    "grows": "Cotton Fabric",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Magician",
    "sell_to_id": 82
  },
  {
    "seed_id": 777,
    "level": 4,
    "cost": 2,
    "xp": 10,
    "time": 5,
    "sells_for": 1,
    "seed": "Tomato Seed",
    "grows_id": 3,
    "grows": "Tomato",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Outpost Trader",
    "sell_to_id": 12
  },
  {
    "seed_id": 759,
    "level": 5,
    "cost": 2,
    "xp": 12,
    "time": 6,
    "sells_for": 7,
    "seed": "Hay Seed",
    "grows_id": 758,
    "grows": "Hay",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Farmer",
    "sell_to_id": 182
  },
  {
    "seed_id": 761,
    "level": 7,
    "cost": 15,
    "xp": 16,
    "time": 8,
    "sells_for": 19,
    "seed": "Wheat Seed",
    "grows_id": 760,
    "grows": "Wheat",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Farmer",
    "sell_to_id": 182
  },
  {
    "seed_id": 763,
    "level": 8,
    "cost": 25,
    "xp": 16,
    "time": 8,
    "sells_for": 30,
    "seed": "Apple Tree Seed",
    "grows_id": 762,
    "grows": "Apple",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "Dorpat Farmer",
    "sell_to_id": 182
  },
  {
    "seed_id": 787,
    "level": 13,
    "cost": 35,
    "xp": 20,
    "time": 9,
    "sells_for": 20,
    "seed": "Potato Seed",
    "grows_id": 780,
    "grows": "Potato",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Narwa Farmer",
    "sell_to_id": 242
  },
  {
    "seed_id": 778,
    "level": 15,
    "cost": 130,
    "xp": 24,
    "time": 10,
    "sells_for": 100,
    "seed": "Yarrow Leaf Seed",
    "grows_id": 283,
    "grows": "Yarrow",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Reval Alchemist",
    "sell_to_id": 77
  },
  {
    "seed_id": 788,
    "level": 17,
    "cost": 70,
    "xp": 26,
    "time": 10,
    "sells_for": 42,
    "seed": "Onion Seed",
    "grows_id": 781,
    "grows": "Onion",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Narwa Farmer",
    "sell_to_id": 242
  },
  {
    "seed_id": 1035,
    "level": 20,
    "cost": 716,
    "xp": 28,
    "time": 13,
    "sells_for": 448,
    "seed": "Bamboo Seed",
    "grows_id": 266,
    "grows": "Bamboo Fabric",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Reval Magician",
    "sell_to_id": 83
  },
  {
    "seed_id": 3158,
    "level": 20,
    "cost": 60,
    "xp": 28,
    "time": 13,
    "sells_for": "",
    "seed": "Cotton Tree Seed",
    "grows_id": 3152,
    "grows": "Feather Cotton",
    "buy_from": "Dorpat Farmer",
    "buy_from_id": 182,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 4000,
    "level": 20,
    "cost": "",
    "xp": 200,
    "time": 12,
    "sells_for": "",
    "seed": "Firework Seed",
    "grows_id": 3792,
    "grows": "Firework",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 776,
    "level": 25,
    "cost": 220,
    "xp": 30,
    "time": 13,
    "sells_for": 150,
    "seed": "Oregano Leaf Seed",
    "grows_id": 284,
    "grows": "Oregano Leaf",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Walco Alchemist",
    "sell_to_id": 218
  },
  {
    "seed_id": 789,
    "level": 28,
    "cost": 95,
    "xp": 32,
    "time": 13,
    "sells_for": 50,
    "seed": "Banana Tree Seed",
    "grows_id": 782,
    "grows": "Banana",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Narwa Farmer",
    "sell_to_id": 242
  },
  {
    "seed_id": 794,
    "level": 30,
    "cost": 220,
    "xp": 35,
    "time": 13,
    "sells_for": 65,
    "seed": "Old Leaves Seed",
    "grows_id": 228,
    "grows": "Old Leaf",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Reval Alchemist",
    "sell_to_id": 77
  },
  {
    "seed_id": 3213,
    "level": 30,
    "cost": "",
    "xp": 300,
    "time": 120,
    "sells_for": "",
    "seed": "Sorrow Tree Seed",
    "grows_id": 3213,
    "grows": "Sorrow Tree Seed",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 3212,
    "level": 30,
    "cost": "",
    "xp": 650,
    "time": 180,
    "sells_for": "",
    "seed": "Rose Tree Seed",
    "grows_id": 3212,
    "grows": "Rose Tree Seed",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 3211,
    "level": 30,
    "cost": "",
    "xp": 1500,
    "time": 400,
    "sells_for": "",
    "seed": "Heart Tree Seed",
    "grows_id": 3211,
    "grows": "Heart Tree Seed",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 790,
    "level": 36,
    "cost": 110,
    "xp": 38,
    "time": 14,
    "sells_for": 70,
    "seed": "Pineapple Seed",
    "grows_id": 783,
    "grows": "Pineapple",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Narwa Farmer",
    "sell_to_id": 242
  },
  {
    "seed_id": 3159,
    "level": 40,
    "cost": 1800,
    "xp": 40,
    "time": 14,
    "sells_for": "",
    "seed": "Angel Tree Seed",
    "grows_id": 3153,
    "grows": "Angel Cotton",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 4157,
    "level": 40,
    "cost": 15000,
    "xp": 300,
    "time": 120,
    "sells_for": "",
    "seed": "Eggplant Seed",
    "grows_id": 4149,
    "grows": "Eggplant",
    "buy_from": "Tavern Shopkeeper",
    "buy_from_id": 442,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 773,
    "level": 45,
    "cost": 300,
    "xp": 45,
    "time": 14,
    "sells_for": 200,
    "seed": "Blue Leaf Seed",
    "grows_id": 212,
    "grows": "Blue Leaf",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "Rakblood Alchemist",
    "sell_to_id": 206
  },
  {
    "seed_id": 791,
    "level": 48,
    "cost": 100,
    "xp": 50,
    "time": 13,
    "sells_for": 65,
    "seed": "Carrot Seed",
    "grows_id": 784,
    "grows": "Carrot",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Wandering Farmer",
    "sell_to_id": 243
  },
  {
    "seed_id": 792,
    "level": 55,
    "cost": 160,
    "xp": 62,
    "time": 16,
    "sells_for": 100,
    "seed": "Corn Seed",
    "grows_id": 785,
    "grows": "Corn",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Wandering Farmer",
    "sell_to_id": 243
  },
  {
    "seed_id": 3160,
    "level": 60,
    "cost": 1800,
    "xp": 62,
    "time": 16,
    "sells_for": "",
    "seed": "Devil Tree Seed",
    "grows_id": 3154,
    "grows": "Devil Cotton",
    "buy_from": "Narwa Farmer",
    "buy_from_id": 242,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 793,
    "level": 62,
    "cost": 250,
    "xp": 67,
    "time": 17,
    "sells_for": 175,
    "seed": "Strawberry Seed",
    "grows_id": 786,
    "grows": "Strawberry",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Wandering Farmer",
    "sell_to_id": 243
  },
  {
    "seed_id": 774,
    "level": 65,
    "cost": 380,
    "xp": 70,
    "time": 17,
    "sells_for": 290,
    "seed": "Aconitum Seed",
    "grows_id": 285,
    "grows": "Aconitum",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Walco Alchemist",
    "sell_to_id": 218
  },
  {
    "seed_id": 1364,
    "level": 66,
    "cost": 800,
    "xp": 75,
    "time": 18,
    "sells_for": 1502,
    "seed": "Flannel Seed",
    "grows_id": 1012,
    "grows": "Flannel Fabric",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Blood River Magic Crafter",
    "sell_to_id": 267
  },
  {
    "seed_id": 775,
    "level": 67,
    "cost": 500,
    "xp": 100,
    "time": 24,
    "sells_for": 400,
    "seed": "Blood Herb Seed",
    "grows_id": 221,
    "grows": "Blood Herb",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Walco Alchemist",
    "sell_to_id": 218
  },
  {
    "seed_id": 854,
    "level": 69,
    "cost": 1300,
    "xp": 145,
    "time": 34,
    "sells_for": 1000,
    "seed": "Beast Herb Seed",
    "grows_id": 222,
    "grows": "Beast Herb",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Walco Alchemist",
    "sell_to_id": 218
  },
  {
    "seed_id": 1015,
    "level": 80,
    "cost": "",
    "xp": 170,
    "time": 38,
    "sells_for": 2000,
    "seed": "Dragon Herb Seed",
    "grows_id": 229,
    "grows": "Dragon Herb",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "Walco Alchemist",
    "sell_to_id": 218
  },
  {
    "seed_id": 3161,
    "level": 80,
    "cost": 4000,
    "xp": 180,
    "time": 38,
    "sells_for": "",
    "seed": "Ice Tree Seed",
    "grows_id": 3155,
    "grows": "Ice Cotton",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 1358,
    "level": 85,
    "cost": 3801,
    "xp": 190,
    "time": 40,
    "sells_for": 2376,
    "seed": "Tossa Jute Seed",
    "grows_id": 1013,
    "grows": "Jute Fabric",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Heaven Magic Crafter",
    "sell_to_id": 268
  },
  {
    "seed_id": 1359,
    "level": 95,
    "cost": 5520,
    "xp": 240,
    "time": 50,
    "sells_for": 3450,
    "seed": "Bag of Worms",
    "grows_id": 1014,
    "grows": "Silk Fabric",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "Heaven Magic Crafter",
    "sell_to_id": 268
  },
  {
    "seed_id": 3162,
    "level": 100,
    "cost": 7500,
    "xp": 250,
    "time": 50,
    "sells_for": "",
    "seed": "Lightning Tree Seed",
    "grows_id": 3156,
    "grows": "Lightning Cotton",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 3382,
    "level": 110,
    "cost": "",
    "xp": 320,
    "time": 60,
    "sells_for": "",
    "seed": "Golden Apple Tree Seed",
    "grows_id": 981,
    "grows": "Golden Apple",
    "buy_from": "",
    "buy_from_id": "",
    "sell_to": "",
    "sell_to_id": ""
  },
  {
    "seed_id": 3163,
    "level": 120,
    "cost": 10000,
    "xp": 450,
    "time": 75,
    "sells_for": "",
    "seed": "Phoenix Tree Seed",
    "grows_id": 3157,
    "grows": "Phoenix Cotton",
    "buy_from": "Wandering Farmer",
    "buy_from_id": 243,
    "sell_to": "",
    "sell_to_id": ""
  }
]
export default farmingData;